spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port = 8080

jwt.secret=7fca38b4d89a42e1b1068c764e5d2b93dfae12984b361a7c0d5e8f421a9c3b8e
jwt.expiration-ms=3600000